//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.customer_contact = new HashSet<customer_contact>();
            this.procure = new HashSet<procure>();
            this.supplyer_contact = new HashSet<supplyer_contact>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<customer_contact> customer_contact { get; set; }
        public virtual ICollection<procure> procure { get; set; }
        public virtual ICollection<supplyer_contact> supplyer_contact { get; set; }
    }
}
