//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.repair_item_detail = new HashSet<repair_item_detail>();
            this.staff = new HashSet<staff>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<repair_item_detail> repair_item_detail { get; set; }
        public virtual ICollection<staff> staff { get; set; }
    }
}
