//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class express
    {
        public express()
        {
            this.sale = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<sale> sale { get; set; }
    }
}
