//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public sale()
        {
            this.sale_detail = new HashSet<sale_detail>();
            this.shelf_io = new HashSet<shelf_io>();
        }
    
        public int id { get; set; }
        public int branch_id { get; set; }
        public int stuff_id { get; set; }
        public int customer_id { get; set; }
        public decimal parts_price { get; set; }
        public Nullable<decimal> express_fee { get; set; }
        public Nullable<int> express_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual express express { get; set; }
        public virtual ICollection<sale_detail> sale_detail { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<shelf_io> shelf_io { get; set; }
    }
}
