//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelf
    {
        public shelf()
        {
            this.shelf_io = new HashSet<shelf_io>();
        }
    
        public int id { get; set; }
        public int branch_id { get; set; }
        public string barcode { get; set; }
        public string name { get; set; }
        public int goods_id { get; set; }
        public decimal quantity { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual goods goods { get; set; }
        public virtual ICollection<shelf_io> shelf_io { get; set; }
    }
}
