//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMgrWeb.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelf_io
    {
        public shelf_io()
        {
            this.repair_parts = new HashSet<repair_parts>();
            this.sale_detail = new HashSet<sale_detail>();
        }
    
        public int id { get; set; }
        public Nullable<int> repair_id { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> procure_id { get; set; }
        public Nullable<int> inventory_id { get; set; }
        public int shelf_id { get; set; }
        public decimal quantity { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual procure procure { get; set; }
        public virtual repair repair { get; set; }
        public virtual ICollection<repair_parts> repair_parts { get; set; }
        public virtual sale sale { get; set; }
        public virtual ICollection<sale_detail> sale_detail { get; set; }
        public virtual shelf shelf { get; set; }
    }
}
