//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoMgrDbEntities : DbContext
    {
        public AutoMgrDbEntities()
            : base("name=AutoMgrDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barcode_goods> barcode_goods { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_contact> customer_contact { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<express> express { get; set; }
        public virtual DbSet<goods> goods { get; set; }
        public virtual DbSet<goods_alias> goods_alias { get; set; }
        public virtual DbSet<goods_photo> goods_photo { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<procure> procure { get; set; }
        public virtual DbSet<procure_detail> procure_detail { get; set; }
        public virtual DbSet<repair> repair { get; set; }
        public virtual DbSet<repair_cate> repair_cate { get; set; }
        public virtual DbSet<repair_cate_item> repair_cate_item { get; set; }
        public virtual DbSet<repair_item> repair_item { get; set; }
        public virtual DbSet<repair_item_detail> repair_item_detail { get; set; }
        public virtual DbSet<repair_parts> repair_parts { get; set; }
        public virtual DbSet<repair_photo> repair_photo { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<sale_detail> sale_detail { get; set; }
        public virtual DbSet<shelf> shelf { get; set; }
        public virtual DbSet<shelf_io> shelf_io { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<supplyer> supplyer { get; set; }
        public virtual DbSet<supplyer_contact> supplyer_contact { get; set; }
        public virtual DbSet<vehicle> vehicle { get; set; }
    }
}
