//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.inventory = new HashSet<inventory>();
            this.procure = new HashSet<procure>();
            this.repair = new HashSet<repair>();
            this.shelf = new HashSet<shelf>();
            this.staff = new HashSet<staff>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<inventory> inventory { get; set; }
        public virtual ICollection<procure> procure { get; set; }
        public virtual ICollection<repair> repair { get; set; }
        public virtual ICollection<shelf> shelf { get; set; }
        public virtual ICollection<staff> staff { get; set; }
    }
}
