//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customer_contact = new HashSet<customer_contact>();
            this.repair = new HashSet<repair>();
            this.sale = new HashSet<sale>();
            this.vehicle = new HashSet<vehicle>();
        }
    
        public int id { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<customer_contact> customer_contact { get; set; }
        public virtual ICollection<repair> repair { get; set; }
        public virtual ICollection<sale> sale { get; set; }
        public virtual ICollection<vehicle> vehicle { get; set; }
    }
}
