//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public inventory()
        {
            this.shelf_io = new HashSet<shelf_io>();
        }
    
        public int id { get; set; }
        public int branch_id { get; set; }
        public System.DateTime date { get; set; }
        public int staff_id { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<shelf_io> shelf_io { get; set; }
    }
}
