//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class procure_detail
    {
        public int id { get; set; }
        public int procure_id { get; set; }
        public int goods_id { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual procure procure { get; set; }
    }
}
