//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplyer_contact
    {
        public int id { get; set; }
        public int supplyer_id { get; set; }
        public int contact_id { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual supplyer supplyer { get; set; }
    }
}
